# Generated by Django 4.1.3 on 2022-12-03 04:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0005_encargados'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Encargados',
            new_name='Responsables',
        ),
    ]
