# Generated by Django 4.1.2 on 2022-12-03 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_rename_encargados_responsables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsables',
            name='correo',
        ),
    ]
