# Generated by Django 4.1.2 on 2022-12-03 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_remove_responsables_correo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnos',
            name='correo',
        ),
    ]
